### PR TITLE
Add Gradle build system

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
Great project! I added build facilities so this can be compiled into a JAR easily.

The examples (`app`) folder is excluded, as it isn't suitable to be included in a library.

### CODE REVIEW

**Comment by nayuki** [comment]
Sorry, this is a massive change and I don't know the Gradle build system. There is no way for me to verify the quality of this code contribution.

**Comment by ishitatsuyuki** [comment]
Everything except build.gradle are autogenerated, and they are only for bootstrap. I hope this clarifies it for you.

**Comment by nayuki** [comment]
I see. This contradicts my understated goal of having short, simple, plainly auditable code. The patch complexity is a liability and who knows what could be hiding in there?

**Comment by ishitatsuyuki** [comment]
I understand your goal, however this is the sad convention of every Gradle based project. The bootstrap code are basically there to be able to execute the build without preinstalling any build tool globally.

That being said, these generated code should be completely reproducible (I assume it's identical to what Gradle's source include).

**Comment by ishitatsuyuki** [comment]
At your option, it's also possible to remove the (complex) wrapper files and rely on a system installation of Gradle. Would you accept in that form?

**Comment by nayuki** [comment]
I'm going to take a look at setting up Maven instead.

**Pull request closed without merging**
